# Generated by Django 3.2.18 on 2023-06-07 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('memo', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('wb', 'Web'), ('mb', 'Mobile'), ('dt', 'Data'), ('db', 'Data Base'), ('gm', 'Game'), ('ai', 'AI'), ('cs', 'CS'), ('et', 'etc')], default='et', max_length=2)),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=30)),
                ('image', models.URLField(blank=True, null=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
